# fly.toml app configuration file generated for iphone-image-api on 2024-08-15T22:46:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iphone-image-api'
primary_region = 'sea'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
